




.build/leonardo/src/arduinolux.cpp : src/arduinolux.ino
	@mkdir -p .build/leonardo/src
	@echo [93msrc/arduinolux.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/leonardo/src/arduinolux.cpp
	@true

